[project]
name = "trees"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.42.2",
    "streamlit-flow-component>=1.6.1",
]

[tool.ruff]
line_length = 100